### ISSUE TITLE
ImportError: No module named '_pandasujson'

### ISSUE THREAD

**Issue by ahmadia** [cloudpipe/cloudpickle#106]
As I mentioned in https://github.com/cloudpipe/cloudpickle/pull/80, a change introduced after 0.2.2 breaks a previously working serialized function call that relied on importing pandas. My suspicion is that serialization of functions that utilize `pandas` may be broken in recent versions of cloudpickle.

Full backtrace from Dask/prep.py:

```
Traceback (most recent call last):
  File "prep.py", line 64, in <module>
    dask.compute(values)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/dask/compatibility.py", line 59, in reraise
    raise exc.with_traceback(tb)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/dask/local.py", line 289, in execute_task
    task, data = loads(task_info)
  File "/Users/aron/anaconda3/envs/parallel/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 840, in subimport
    __import__(name)
ImportError: No module named '_pandasujson'
```

**Comment by ahmadia** [comment]
Let me know if I can help dig further into this!

**Comment by pierreglaser** [comment]
It's been a while now, but does the error still appear?
