### ISSUE TITLE
Failing test_temp_file in cloudpickle_file_test.CloudPickleFileTests

### ISSUE THREAD

**Issue by frenzymadness** [cloudpipe/cloudpickle#114]
Hello.

I am trying to make RPM package from cloudpickle for Fedora and I found one failing test. `test_temp_file in cloudpickle_file_test.CloudPickleFileTests` is failing during RPM build and also in a virtual environment. I've tested it with Python 3.5 and 3.6.

```
======================================================================
ERROR: test_temp_file (tests.cloudpickle_file_test.CloudPickleFileTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lbalhar/Software/cloudpickle/tests/cloudpickle_file_test.py", line 96, in test_temp_file
    newfile = pickle.loads(cloudpickle.dumps(f))
  File "/home/lbalhar/Software/cloudpickle/cloudpickle/cloudpickle.py", line 900, in dumps
    cp.dump(obj)
  File "/home/lbalhar/Software/cloudpickle/cloudpickle/cloudpickle.py", line 234, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib64/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib64/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: cannot serialize '_io.BufferedRandom' object

----------------------------------------------------------------------
Ran 48 tests in 1.698s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=48 errors=1 failures=0>
```
Let me know if I can help you with anything.

**Comment by frenzymadness** [comment]
There are still three failing tests:
```
=================================== FAILURES ===================================
___________ CloudPickleFileTests.test_pickling_special_file_handles ____________

self = <tests.cloudpickle_file_test.CloudPickleFileTests testMethod=test_pickling_special_file_handles>

    def test_pickling_special_file_handles(self):
        # Warning: if you want to run your tests with nose, add -s option
        for out in sys.stdout, sys.stderr:  # Regression test for SPARK-3415
>           self.assertEqual(out, pickle.loads(cloudpickle.dumps(out)))

tests/cloudpickle_file_test.py:87: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cloudpickle/cloudpickle_fast.py:73: in dumps
    cp.dump(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cloudpickle.cloudpickle_fast.CloudPickler object at 0x7f0ae8cb6c40>
obj = <_io.TextIOWrapper name="<_io.FileIO name=6 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>

    def dump(self, obj):
        try:
>           return Pickler.dump(self, obj)
E           TypeError: cannot pickle 'EncodedFile' object

cloudpickle/cloudpickle_fast.py:563: TypeError
__________________ CloudPickleTest.test_pickling_file_handles __________________

self = <tests.cloudpickle_test.CloudPickleTest testMethod=test_pickling_file_handles>

    def test_pickling_file_handles(self):
        out1 = sys.stderr
>       out2 = pickle.loads(cloudpickle.dumps(out1, protocol=self.protocol))

tests/cloudpickle_test.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cloudpickle/cloudpickle_fast.py:73: in dumps
    cp.dump(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cloudpickle.cloudpickle_fast.CloudPickler object at 0x7f0ae87fb040>
obj = <_io.TextIOWrapper name="<_io.FileIO name=8 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>

    def dump(self, obj):
        try:
>           return Pickler.dump(self, obj)
E           TypeError: cannot pickle 'EncodedFile' object

cloudpickle/cloudpickle_fast.py:563: TypeError
_____________ Protocol2CloudPickleTest.test_pickling_file_handles ______________

self = <tests.cloudpickle_test.Protocol2CloudPickleTest testMethod=test_pickling_file_handles>

    def test_pickling_file_handles(self):
        out1 = sys.stderr
>       out2 = pickle.loads(cloudpickle.dumps(out1, protocol=self.protocol))

tests/cloudpickle_test.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cloudpickle/cloudpickle_fast.py:73: in dumps
    cp.dump(obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cloudpickle.cloudpickle_fast.CloudPickler object at 0x7f0ae8a6ad00>
obj = <_io.TextIOWrapper name="<_io.FileIO name=8 mode='rb+' closefd=True>" mode='r+' encoding='utf-8'>

    def dump(self, obj):
        try:
>           return Pickler.dump(self, obj)
E           TypeError: cannot pickle 'EncodedFile' object

cloudpickle/cloudpickle_fast.py:563: TypeError
=========================== short test summary info ============================
FAILED tests/cloudpickle_file_test.py::CloudPickleFileTests::test_pickling_special_file_handles
FAILED tests/cloudpickle_test.py::CloudPickleTest::test_pickling_file_handles
FAILED tests/cloudpickle_test.py::Protocol2CloudPickleTest::test_pickling_file_handles
================== 3 failed, 215 passed, 13 skipped in 9.05s ===================
```

Tested with Python 3.9 and cloudpickle 1.6.0

**Comment by ArchangeGabriel** [comment]
I have the same three failing tests in a similar environment.
