### ISSUE TITLE
Can't unpickle functions using namedtuple

### ISSUE THREAD

**Issue by rshin** [cloudpipe/cloudpickle#119]
On Python 2.7.12 with cloudpickle 0.4.0:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> X = collections.namedtuple('X', ['x', 'y'])
>>> def f(): return X(1, 2)
...
>>> import cloudpickle
>>> cloudpickle.loads(cloudpickle.dumps(f))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/home/richard/.local/share/virtualenvs/cloudpickle/local/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 1053, in _rehydrate_skeleton_class
    setattr(skeleton_class, attrname, attr)
AttributeError: attribute '__dict__' of 'type' objects is not writable
>>> cloudpickle.__version__
'0.4.0'
```

**Comment by robertnishihara** [comment]
Related to #111.

**Comment by rgbkrk** [comment]
`v0.4.1` is out, take it for a spin for your `namedtuple` needs.

**Comment by robertnishihara** [comment]
Yep seems to work nicely, thanks a lot!
