### ISSUE TITLE
Tests fail on FreeBSD (version 0.5.2)

### ISSUE THREAD

**Issue by yurivict** [cloudpipe/cloudpickle#143]
```
test_weakset_identity_preservation (tests.cloudpickle_test.Protocol2CloudPickleTest) ... ok

======================================================================
ERROR: test_sliced_and_non_contiguous_memoryview (tests.cloudpickle_test.CloudPickleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/devel/py-cloudpickle/work-py27/cloudpickle-0.5.2/tests/cloudpickle_test.py", line 144, in test_sliced_and_non_contiguous_memoryview
    buffer_obj = memoryview(b"Hello!" * 3)[2:15:2]
NotImplementedError

======================================================================
ERROR: test_sliced_and_non_contiguous_memoryview (tests.cloudpickle_test.Protocol2CloudPickleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/devel/py-cloudpickle/work-py27/cloudpickle-0.5.2/tests/cloudpickle_test.py", line 144, in test_sliced_and_non_contiguous_memoryview
    buffer_obj = memoryview(b"Hello!" * 3)[2:15:2]
NotImplementedError

----------------------------------------------------------------------
Ran 110 tests in 7.590s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=110 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=110 errors=2 failures=0>
*** Error code 1

```

**Comment by koobs** [comment]
I can't reproduce/see these test failures with 1.1.0  (or 0.8.1, current port version) on FreeBSD

**Comment by yurivict** [comment]
Yes, they don't fail any more, now in ```0.8.1```.
