### ISSUE TITLE
Can not pickle interactively defined property types

### ISSUE THREAD

**Issue by GreatYYX** [cloudpipe/cloudpickle#243]
I was using Dask Distributed and found a weird exception. After tracking down, it was caused by cloudpickle. The minimal implementation is like below:

```python
import cloudpickle

class dec(property):
    def __init__(self, func):
        self.func = func

    def __get__(self, obj, cls):
        if obj is None:
            return self

        return 'dec_{}'.format(self.func(obj))

class TestClass():
    def __init__(self, x):
        self.x = x

    @dec
    def test_property(self):
        return self.x

t = TestClass('test')
print(t.test_property)
cloudpickle.dumps(t)
```

Traceback info:
```
Traceback (most recent call last):
  File "/Users/test/main.py", line 23, in <module>
    cloudpickle.dumps(t)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 931, in dumps
    cp.dump(obj)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 284, in dump
    return Pickler.dump(self, obj)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 605, in save_reduce
    save(cls)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 678, in save_global
    return self.save_dynamic_class(obj)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 517, in save_dynamic_class
    save(clsdict)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)
  File "/Users/test/anaconda2/envs/py36/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle dec objects
```

But if I define `TestClass` in a module instead of `__main__`, it works.

mod_a.py
```
class dec(property):
    def __init__(self, func):
        self.func = func

    def __get__(self, obj, cls):
        if obj is None:
            return self

        return 'dec_{}'.format(self.func(obj))

class TestClass():
    def __init__(self, x):
        self.x = x

    @dec
    def test_property(self):
        return self.x
```

main.py
```
import cloudpickle
from mod_a import *

t = TestClass('test')
print(t.test_property)
cloudpickle.dumps(t)
```

**Comment by GreatYYX** [comment]
Thank you for your prompt reply and explanation, Olivier.

Like you said, `dec` itself is used as a type. I don't know how cloudpickle handles interactively defined class, but is it possible for it to support interactively defined property type? e.g., pickle the property type and add this type into `dispatch` table.

**Comment by GreatYYX** [comment]
Thank your so much @pierreglaser . You specific solution works great.

One thing I don't quite understand here is why `property` makes subclasses "purposely throw a `TypeError`". (was it defined here? https://github.com/python/cpython/blob/master/Objects/descrobject.c)

BTW, `pickle.dumps` works for both class and instance.

**Comment by ogrisel** [comment]
@GreatYYX the default pickle module in the standard library is not meant to pickle interactively defined Python classes / types so there is no real usecase for adding pickling support to property objects. I think this is why they did not implement pickling support for this purposefully.

**Comment by ogrisel** [comment]
Let's close this as I think we will not be able to give a generic way to solve this issue in cloudpickle itself.
