### ISSUE TITLE
"import cloudpickle" fails  with Python-3.8.0a4

### ISSUE THREAD

**Issue by stonebig** [cloudpipe/cloudpickle#266]
when trying this on python-3.8.0a4 and cloudpickle-1.0.0, on Windows:

````
import cloudpickle
````

I get that error:

![image](https://user-images.githubusercontent.com/4312421/57566795-a8915780-73d0-11e9-8d7d-1cd022db1b46.png)

**Comment by stonebig** [comment]
same error for this:
````
# ipyleaflet (javascript library usage)
from ipyleaflet import (
    Map, Marker, TileLayer, ImageOverlay, Polyline, Polygon,
    Rectangle, Circle, CircleMarker, GeoJSON, DrawControl
)
from traitlets import link
center = [34.6252978589571, -77.34580993652344]
m = Map(center=[34.6252978589571, -77.34580993652344], zoom=10)
dc = DrawControl()

def handle_draw(self, action, geo_json):
    print(action)
    print(geo_json)
m
m
````

i get 
````
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-7979e6f84658> in <module>
      1 # ipyleaflet (javascript library usage)
----> 2 from ipyleaflet import (
      3     Map, Marker, TileLayer, ImageOverlay, Polyline, Polygon,
      4     Rectangle, Circle, CircleMarker, GeoJSON, DrawControl
      5 )

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\ipyleaflet\__init__.py in <module>
      5 
      6 try:
----> 7     from .leaflet import *
      8 except ImportError:
      9     pass

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\ipyleaflet\leaflet.py in <module>
    296 
    297 
--> 298 class Velocity(Layer):
    299     _view_name = Unicode('LeafletVelocityView').tag(sync=True)
    300     _model_name = Unicode('LeafletVelocityModel').tag(sync=True)

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\ipyleaflet\leaflet.py in Velocity()
    306     units = Unicode(None, allow_none=True)
    307 
--> 308     data = Dataset().tag(sync=True, to_json=ds_x_to_json)
    309 
    310     # Options

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\traittypes\traittypes.py in __init__(self, default_value, allow_none, dtype, **kwargs)
    263     def __init__(self, default_value=Empty, allow_none=False, dtype=None, **kwargs):
    264         if 'klass' not in kwargs and self.klass is None:
--> 265             import xarray as xr
    266             kwargs['klass'] = xr.Dataset
    267         super(Dataset, self).__init__(

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\xarray\__init__.py in <module>
      5 del get_versions
      6 
----> 7 from .core.alignment import align, broadcast, broadcast_arrays
      8 from .core.common import full_like, zeros_like, ones_like
      9 from .core.combine import concat, auto_combine

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\xarray\core\alignment.py in <module>
      9 import pandas as pd
     10 
---> 11 from . import utils
     12 from .indexing import get_indexer_nd
     13 from .utils import is_dict_like, is_full_slice

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\xarray\core\utils.py in <module>
     13 import pandas as pd
     14 
---> 15 from .pycompat import dask_array_type
     16 
     17 

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\xarray\core\pycompat.py in <module>
      9 try:
     10     # solely for isinstance checks
---> 11     import dask.array
     12     dask_array_type = (dask.array.Array,)
     13 except ImportError:  # pragma: no cover

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\dask\__init__.py in <module>
      6 from .local import get_sync as get
      7 try:
----> 8     from .delayed import delayed
      9 except ImportError:
     10     pass

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\dask\delayed.py in <module>
     12 
     13 from . import config, threaded
---> 14 from .base import is_dask_collection, dont_optimize, DaskMethodsMixin
     15 from .base import tokenize as _tokenize
     16 from .compatibility import apply, Iterator, is_dataclass, dataclass_fields

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\dask\base.py in <module>
    825 
    826 try:
--> 827     from dask import multiprocessing as dask_multiprocessing
    828 except ImportError:
    829     pass

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\dask\multiprocessing.py in <module>
      7 from warnings import warn
      8 
----> 9 import cloudpickle
     10 
     11 from . import config

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from cloudpickle.cloudpickle import *
      4 
      5 __version__ = '1.0.0'

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py in <module>
    150 
    151 
--> 152 _cell_set_template_code = _make_cell_set_template_code()
    153 
    154 

C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py in _make_cell_set_template_code()
    131         )
    132     else:
--> 133         return types.CodeType(
    134             co.co_argcount,
    135             co.co_kwonlyargcount,

TypeError: an integer is required (got type bytes)
````

**Comment by stonebig** [comment]
I'm not sure if it's a cloupickle or joblib "Python-3.7.0a4" alpha on windows issue, but this combination seems widely used in scientific package.

**Comment by stonebig** [comment]
Pep574 is not implemented yet, so it's not the issue https://www.python.org/dev/peps/pep-0574

**Comment by stonebig** [comment]
i'm not expert in test... how do I launch the cloupickle test on a command line on windows ?

**Comment by stonebig** [comment]
when I add a print.. well, I don't  quite understant what I see:
````
    else:
        print (
            co.co_argcount,
            co.co_kwonlyargcount,
            co.co_nlocals,
            co.co_stacksize,
            co.co_flags,
            co.co_code,
            co.co_consts,
            co.co_names,
            co.co_varnames,
            co.co_filename,
            co.co_name,
            co.co_firstlineno,
            co.co_lnotab,
            co.co_cellvars)
````


````
>>> import cloudpickle
1 0 1 3 19 b'\x87\x00f\x01d\x01d\x02\x84\x08\x01\x00|\x00\x89\x00d\x00S\x00' (None, <code object <lambda> at 0x0000016EC17B1328, file "C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py", line 107>, '_make_cell_set_template_code.<locals>.inner.<locals>.<lambda>') () ('value',) C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py inner 106 b'\x00\x01\x0c\x01' ('cell',)
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import cloudpickle
  File "C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\__init__.py", line 3, in <module>
    from cloudpickle.cloudpickle import *
  File "C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "C:\WinP\bd38\bu\WPy64-3800a4\python-3.8.0a4.amd64\lib\site-packages\cloudpickle\cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)````

**Comment by stonebig** [comment]
posted also on https://bugs.python.org/issue36886 , as maybe it's a python issue

**Comment by stonebig** [comment]
There may be code to change because of PEP 570

**Comment by stonebig** [comment]
would it be possible to include the change in vendored joblib ?
