### ISSUE TITLE
Cannot pickle attrs classes

### ISSUE THREAD

**Issue by Lingepumpe** [cloudpipe/cloudpickle#320]
```
from attr import attrs, attrib
import cloudpickle

@attrs
class Foo:
    x = attrib()

cloudpickle.dumps(Foo)
```
Fails with `TypeError: cannot pickle 'property' object` for me.
python 3.8.1, attrs = "19.3.0", cloudpickle = "1.2.2"

As mentioned here: https://github.com/python-attrs/attrs/issues/458 there is also some issue with 
`TypeError: cannot pickle '_thread._local' object` that can be worked around by using `@attrs(repr=False)`. The repr fix does not help with the above.

See below for a snipet to reproduce the `TypeError: cannot pickle '_thread._local' object`:
```
from attr import attrs
import cloudpickle

@attrs
class Foo:
    pass

cloudpickle.dumps(Foo)
```

**Comment by ogrisel** [comment]
I am not sure if it's a bug, a regression or a missing feature but someone should definitely investigate :) Thanks for the report.

**Comment by Lingepumpe** [comment]
At least the first part with `TypeError: cannot pickle 'property' object` might be a duplicate of issue #321 [or vice versa] - the python version and error message are the same.

The second part of the ticket (with `TypeError: cannot pickle '_thread._local' object`) is attrs specific and less critical due to a work-around via repr=False being known.

**Comment by ogrisel** [comment]
I thought  #321 was only about Python 3.6 while this issue is reported for 3.8.1. Will need to investigate but cannot do it in the short term.

**Comment by Lingepumpe** [comment]
With the merge of @pierreglaser MR ( 8f851f727670849dcee33134f6497f1ff84a0aad ) now *both* of my above test-cases produce the same output: 
`TypeError: cannot pickle '_thread._local' object`. It seems the python-3.8 specific bug has been fixed and the attr specific bug is the only thing remaining. As mentioned above requesting no repr function to be generated by attr is a workaround, when supplying `@attrs(repr=False)` as the class decorator cloudpickle manages to dump the class.

**Comment by danpf** [comment]
Hello,

I was looking at this and found that for some reason I cannot recreate the thread.local error in pytest.  I was wondering if anyone had any thoughts on why that is? or possibly the solution! 

for reference the stdout/err is:
```
# pytest tests/cloudpickle_test.py -k test_attr
tests/cloudpickle_test.py b'\x80\x05\x95"\x00\x00\x00\x00\x00\x00\x00\x8c\x16tests.cloudpickle_test\x94\x8c\x03Foo\x94\x93\x94.'
Traceback (most recent call last):
  File "hello.py", line 6, in <module>
    print(cloudpickle.dumps(Foo))
  File "/home/danpf/git/cloudpickle/cloudpickle/cloudpickle_fast.py", line 64, in dumps
    cp.dump(obj)
  File "/home/danpf/git/cloudpickle/cloudpickle/cloudpickle_fast.py", line 549, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread._local' object

======================================================================================== FAILURES ========================================================================================
_______________________________________________________________________________ CloudPickleTest.test_attr ________________________________________________________________________________

self = <tests.cloudpickle_test.CloudPickleTest testMethod=test_attr>

    def test_attr(self):
        print(cloudpickle.dumps(Foo))
        test_str = (
                "import cloudpickle\n"
                "import attr\n"
                "@attr.s\n"
                "class Foo:\n"
                "    x: int = attr.ib()\n"
                "print(cloudpickle.dumps(Foo))\n")
        with open("hello.py", "w") as fh:
            fh.write(test_str)
        ret = subprocess.call(["python", "hello.py"])
>       assert ret == 0
E       AssertionError: assert 1 == 0

```
patch below
```
diff --git a/dev-requirements.txt b/dev-requirements.txt
index 4e26b21..7dcd389 100644
--- a/dev-requirements.txt
+++ b/dev-requirements.txt
@@ -13,3 +13,4 @@ codecov
 coverage
 # Utility package used when running the cloudpickle test suite
 ./tests/cloudpickle_testpkg
+attrs
diff --git a/tests/cloudpickle_test.py b/tests/cloudpickle_test.py
index b1821db..4e9afc3 100644
--- a/tests/cloudpickle_test.py
+++ b/tests/cloudpickle_test.py
@@ -26,6 +26,7 @@ import typing
 from functools import wraps
 
 import pytest
+import attr
 
 try:
     # try importing numpy and scipy. These are not hard dependencies and
@@ -58,6 +59,11 @@ from _cloudpickle_testpkg import relative_imports_factory
 _TEST_GLOBAL_VARIABLE = "default_value"
 
 
+@attr.s
+class Foo:
+    x: int = attr.ib()
+
+
 class RaiserOnPickle(object):
 
     def __init__(self, exc):
@@ -191,6 +197,20 @@ class CloudPickleTest(unittest.TestCase):
         self.assertTrue("exit" in foo.__code__.co_names)
         cloudpickle.dumps(foo)
 
+    def test_attr(self):
+        print(cloudpickle.dumps(Foo))
+        test_str = (
+                "import cloudpickle\n"
+                "import attr\n"
+                "@attr.s\n"
+                "class Foo:\n"
+                "    x: int = attr.ib()\n"
+                "print(cloudpickle.dumps(Foo))\n")
+        with open("hello.py", "w") as fh:
+            fh.write(test_str)
+        ret = subprocess.call(["python", "hello.py"])
+        assert ret == 0
+
     def test_buffer(self):
         try:
             buffer_obj = buffer("Hello")
```

**Comment by ritsuki1227** [comment]
Hi, any update on the issue?
I have a similar problem on the code bellow.

```py
from tenacity import retry
import cloudpickle

@retry
def foo(bar):
    print(bar)
    
cloudpickle.dumps(foo)
```

**Comment by thetorpedodog** [comment]
With [attrs release 21.4.0](https://pypi.org/project/attrs/21.4.0/), this incompatibility has been fixed and attrs instances can be cloudpickled.
