### ISSUE TITLE
cloudpickle v1.5.0 breaks TensorFlow Probability

### ISSUE THREAD

**Issue by matthewfeickert** [cloudpipe/cloudpickle#390]
Hi. I'm just reporting that [`cloudpickle` `v1.5.0`](https://pypi.org/project/cloudpickle/1.5.0/) currently breaks TensorFlow Probability entirely. This is more of a heads up as you'll probably be getting some other reports.

This is currenlty detailed in the following Issues:
- [`pyhf` Issue 913](https://github.com/scikit-hep/pyhf/issues/913)
- [TensorFlow Probability Issue 991](https://github.com/tensorflow/probability/issues/991)

A minimal failing example is found in [`pyhf` Issue 913](https://github.com/scikit-hep/pyhf/issues/913) but also reproduced here:

```
$ python -m venv ${HOME}/.venvs/debug-this
$ source ${HOME}/.venvs/debug-this/bin/activate
(debug-this) $ python -m pip install --upgrade pip setuptools wheel
(debug-this) $ python -m pip install tensorflow tensorflow-probability
(debug-this) $ python -c "import tensorflow_probability"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/__init__.py", line 76, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py", line 23, in <module>
    from tensorflow_probability.python import distributions
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/python/distributions/__init__.py", line 88, in <module>
    from tensorflow_probability.python.distributions.pixel_cnn import PixelCNN
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/python/distributions/pixel_cnn.py", line 37, in <module>
    from tensorflow_probability.python.layers import weight_norm
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/python/layers/__init__.py", line 31, in <module>
    from tensorflow_probability.python.layers.distribution_layer import CategoricalMixtureOfOneHotCategorical
  File "/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/tensorflow_probability/python/layers/distribution_layer.py", line 28, in <module>
    from cloudpickle.cloudpickle import CloudPickler
ImportError: cannot import name 'CloudPickler' from 'cloudpickle.cloudpickle' (/home/feickert/.venvs/debug-this/lib/python3.7/site-packages/cloudpickle/cloudpickle.py)
(debug-this) $ pip list | grep cloudpickle
cloudpickle            1.5.0
```

**Comment by ogrisel** [comment]
CloudPickler should be imported from the top level module:

```python
from cloudpickle import CloudPickler
```

**Comment by matthewfeickert** [comment]
Thank you for the correction!

**Comment by ogrisel** [comment]
@pierreglaser we might need to implement the hack you suggested to implement a Python 3.6 compatible `__getattr__`...

**Comment by pierreglaser** [comment]
Yes most probably.
