### ISSUE TITLE
Can't pickle functions that use the `colour-science` library

### ISSUE THREAD

**Issue by hotplot** [cloudpipe/cloudpickle#523]
When trying to cloudpickle a function that references the [`colour-science`](https://github.com/colour-science/colour) library, the following exception is raised:

```
Traceback (most recent call last):
  File "/home/hrrsxb/aip/x/test.py", line 10, in <module>
    y = cloudpickle.loads(x)
  File "/home/hrrsxb/.cache/pypoetry/virtualenvs/x-Z-zmud14-py3.10/lib/python3.10/site-packages/colour/__init__.py", line 911, in __getattr__
    return super().__getattr__(attribute)
  File "/home/hrrsxb/.cache/pypoetry/virtualenvs/x-Z-zmud14-py3.10/lib/python3.10/site-packages/colour/utilities/deprecation.py", line 361, in __getattr__
    change = self._changes.get(attribute)

    ...
    
  File "/home/hrrsxb/.cache/pypoetry/virtualenvs/x-Z-zmud14-py3.10/lib/python3.10/site-packages/colour/__init__.py", line 911, in __getattr__
    return super().__getattr__(attribute)
  File "/home/hrrsxb/.cache/pypoetry/virtualenvs/x-Z-zmud14-py3.10/lib/python3.10/site-packages/colour/utilities/deprecation.py", line 361, in __getattr__
    change = self._changes.get(attribute)
RecursionError: maximum recursion depth exceeded
```

Minimal code to reproduce:

```python
import colour
import cloudpickle


def foo():
    print(colour.__version__)


x = cloudpickle.dumps(foo)
y = cloudpickle.loads(x)
```

The issue does not occur when using standard `pickle`

Versions used are:
`python`: 3.10.12
`cloudpickle`: 2.2.1 and 3.0.0 both tested
`colour`: 0.4.3

**Comment by ogrisel** [comment]
The `colour` module is interactively redefined at import time here:

https://github.com/colour-science/colour/blob/v0.4.3/colour/__init__.py#L967

the fake module itself is define here:

https://github.com/colour-science/colour/blob/v0.4.3/colour/__init__.py#L905

and has a generic `__getattr__` to lookup attributes + some class level attributes that are defined a-posteriori when first importing the real module.

I suspect that since it's a fake module, cloudpickle is also trying to pickle it by value instead of pickling it by reference. And the way it's designed it cannot be pickled by value.

Maybe cloudpickle's heuristic to detect what module should be pickled by value could be improved.

Alternatively, `colour` itself might be fixed or improved to make it safe to pickle its fake module by value, for instance by defining the class attributes in the class definition itself rather than by setting them a posteriori.

**Comment by hotplot** [comment]
Closing as this appears to be resolved as of at least `colour` 0.4.6 and `cloudpickle` 3.1.0
