### ISSUE TITLE
cloudpickle.load(file) results in FileNotFoundError

### ISSUE THREAD

**Issue by tslever** [cloudpipe/cloudpickle#525]
I run a Python script on Linux (CentOS and Ubuntu) with a version of the following code.

import os
...
filename = 'name.ext'
assert(os.path.isfile(filename))
with open(filename, 'rb') as file:
    deserialized_object = cloudpickle.load(file)
How do I resolve the following error that I am getting?

Traceback (most recent call last):
  File "/home/tslever/Bayesian_Docking-Score_Predictor/Load_PyMC_Model_And_Training_Inference_Data_And_Create_Visualizations.py", line 155, in <module>
    main(
  File "/home/tslever/Bayesian_Docking-Score_Predictor/Load_PyMC_Model_And_Training_Inference_Data_And_Create_Visualizations.py", line 73, in main
    pymc_model = cloudpickle.load(file)
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 942, in RebuildProxy
    return func(token, serializer, incref=incref, **kwds)
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 792, in __init__
    self._incref()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 846, in _incref
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by ogrisel** [comment]
It's only possible to load a serialized file instance from the same host as the one it was pickled on (or alternatively from an host that has access to same shared filesystem partition).

**Comment by tslever** [comment]
Would you please explain why? I believe I loaded a serialized file instance from the same host on which the instance was pickled. It is possible that I loaded the instance from a different host that has access to my file system partition / node on Rivanna, the University of Virginia’s High Performance Computing system.
