### ISSUE TITLE
Cannot pickle sympy.UndefinedFunction

### ISSUE THREAD

**Issue by asmeurer** [cloudpipe/cloudpickle#65]
sympy.UndefinedFunction creates a dynamic class via a metaclass. See https://github.com/sympy/sympy/blob/20872c3b27726825869876b2dbe38e2fcd3bef2a/sympy/core/function.py#L775

In Python 3, running cloudpickle from a file, I get

``` py
from sympy import Function, symbols

import cloudpickle

f = Function('f')
x = symbols('x')

d = cloudpickle.dumps(f(x))
print(cloudpickle.loads(d))
print(cloudpickle.loads(d) is f(x))
```

``` pytb
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    d = cloudpickle.dumps(f(x))
_pickle.PicklingError: Can't pickle test: attribute lookup test on __main__ failed
```

If I replace `cloudpickle` with `pickle`, it works. 

In Python 2, I get a longer traceback:

``` pytb
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    d = cloudpickle.dumps(f(x))
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 528, in save_reduce
    save(func)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 300, in save
    self.save_global(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 368, in save_global
    self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 533, in save_reduce
    self.memoize(obj)
  File "/Users/aaronmeurer/anaconda3/envs/python2/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
```

**Comment by asmeurer** [comment]
OK, we figured it out, see https://github.com/sympy/sympy/issues/11692 and https://github.com/sympy/sympy/pull/11693. Cloudpickle assumes that metaclasses have the same function signature as `type`, but our custom `__new__` wasn't handling the `type(name, bases, mod_dict)` signature. 

It still fails in Python 2 with my fix, however, so that may be worth looking into.

**Comment by richardotis** [comment]
The Python 2 error looks like a different bug unrelated to the metaclass signature. I can reproduce that traceback with
```python
from sympy import Function
class test(Function):
    pass
cloudpickle.dumps(test)
```
stdlib pickle and dill don't seem to have a problem.

**Comment by ogrisel** [comment]
@richardotis could your reproduce the issue into a test that does not depend on sympy to include into the cloudpickle unittests suite?

**Comment by richardotis** [comment]
@ogrisel This minimal example should raise an AssertionError on Python 2.7. It looks like the problem arises from an interaction between metaclasses and inheritance causing some objects to try to be pickled more than once.

```python
class Meta(object):
    def __new__(mcl, name, *args, **kwargs):
        ret = type(name, (Subclass,), kwargs)
        return ret

class Subclass(Meta):
    pass

class f(Subclass):
    __metaclass__ = Meta

import cloudpickle
cloudpickle.dumps(f)
# AssertionError
```

**Comment by asmeurer** [comment]
A more "correct" implementation should probably incorporate the class dictionary passed to `Meta.__new__` (`args[1]`). Based on the sympy example, this shouldn't affect the issue at hand, however.

**Comment by jakirkham** [comment]
FWIW using the code provided by @richardotis, `dill` version 0.2.5 works fine on Python 2.7, but encounters an `AssertionError` on Python 3.5.

**Comment by jakirkham** [comment]
Should we start looking at `dill` to figure out what they are doing correctly here?

**Comment by jakirkham** [comment]
Have retested this with `cloudpickle` 0.5.2 on Python 3 and the OP code runs fine. Can you please retest @asmeurer when you have a chance?

**Comment by asmeurer** [comment]
Yeah works for me too, in Python 2 and 3.
