### ISSUE TITLE
Problems serializing self-referencing objects

### ISSUE THREAD

**Issue by csachs** [cloudpipe/cloudpickle#66]
Trying to serialize a larger object graph I stumbled upon this problem, here a (non-sensical, albeit error-showing) minimal working example to reproduce the problem. Note, that Python 3.5's built-in `pickle` works fine:

``` python
class SomeClass(object):
    def test(self):
        return SomeClass()

import pickle
import cloudpickle


test = SomeClass()

print(pickle.loads(pickle.dumps(test, pickle.HIGHEST_PROTOCOL)))

print(cloudpickle.loads(cloudpickle.dumps(test)))
```

Results in:

```
<__main__.SomeClass object at 0x7f85ab74e320>
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(cloudpickle.loads(cloudpickle.dumps(test)))
  File "/home/sachs/.local/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/home/sachs/.local/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/usr/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/usr/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/sachs/.local/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 514, in save_reduce
    save(cls)
  File "/usr/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/sachs/.local/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 368, in save_global
    self.save_reduce(typ, (obj.__name__, obj.__bases__, d), obj=obj)
  File "/home/sachs/.local/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 533, in save_reduce
    self.memoize(obj)
  File "/usr/lib/python3.5/pickle.py", line 429, in memoize
    assert id(obj) not in self.memo
AssertionError
```

Tested with cloudpickle 0.2.1 as well as the github version. The problem might be "a different way" to trigger the same underlying problem as in #40 #53 #65.

**Comment by jakirkham** [comment]
Have retested this code with `cloudpickle` version `0.5.2` on Python 3 and this works fine for me. Can you please retest @csachs and confirm whether or not it is still and issue for you?

**Comment by csachs** [comment]
Hi, thanks for checking back on this bug. Yes, can confirm that it's working with `0.5.2` on Python 3. Closing.
