### ISSUE TITLE
Cannot serialize -> deserialize scipy.sparse.dok_matrix

### ISSUE THREAD

**Issue by tkluck-booking** [cloudpipe/cloudpickle#79]
Current behaviour: 
```
>>> import cloudpickle; cloudpickle.__version__
'0.2.2'
>>> from scipy.sparse import dok_matrix
>>> A = dok_matrix((2,2); A
<2x2 sparse matrix of type '<type 'numpy.float64'>'
	with 0 stored elements in Dictionary Of Keys format>
>>> cloudpickle.loads(cloudpickle.dumps(A))
<2x2 sparse matrix of type '<type 'numpy.float64'>'
	with 0 stored elements in Dictionary Of Keys format>
>>> A[0,0] = 1
>>> cloudpickle.loads(cloudpickle.dumps(A))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1204, in load_setitem
    dict[key] = value
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/dok.py", line 235, in __setitem__
    if (isintlike(i) and isintlike(j) and 0 <= i < self.shape[0]
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 525, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found
```
Expected behaviour: an object of type `dok_matrix` properly (de)serializes regardless of content. Note that `pickle` and `cPickle` both work:
```
>>> import pickle
>>> pickle.loads(pickle.dumps(A))
<2x2 sparse matrix of type '<type 'numpy.float64'>'
	with 1 stored elements in Dictionary Of Keys format>
>>> import cPickle
>>> cPickle.loads(cPickle.dumps(A))
<2x2 sparse matrix of type '<type 'numpy.float64'>'
	with 1 stored elements in Dictionary Of Keys format>
```

**Comment by jakirkham** [comment]
Using `cloudpickle` version `0.5.2` on Python 3, am able to run the OP code correctly without exception. Can you please retest and confirm whether this issue is fixed or not, @tkluck-booking?

**Comment by tkluck** [comment]
Hey @jakirkham , thanks for checking and apologies for the delay. I can confirm that this is not reproducible on cloudpickle 0.5.3 and scipy 1.1.0. Feel free to close this issue!

**Comment by jakirkham** [comment]
Thanks for retesting.
