### ISSUE TITLE
cloudpickle.loads returns a bad result on first invocation, correct on second?

### ISSUE THREAD

**Issue by ZmeiGorynych** [cloudpipe/cloudpickle#97]
Hi,

I ran into the following strange issue: I use cloudpickle to serialize my objects to send them to Kafka, and today I saw the following bug: calling cloudpickle.dumps on an object returns a malformed result that I can't load(), but calling it again on the very same object works!

Including the output from the debug console below; the object in question is a pretty big one using internal libraries.

Any idea what might be causing that?

```
import cloudpickle
a = cloudpickle.dumps(self)
b = cloudpickle.dumps(self)
cloudpickle.loads(b)
Out[5]: 
<aiostreams.runner.SendTo at 0x15383bbba20>
cloudpickle.loads(a)
Traceback (most recent call last):
  File "C:\Users\Egor\Anaconda2\envs\py3k\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-c33e741d5197>", line 1, in <module>
    cloudpickle.loads(a)
EOFError: Ran out of input
```

**Comment by ZmeiGorynych** [comment]
Ah got it. My __getstate__ function was throwing an error on first invocation, leaving the object in a state that let it succeed on second call :)
